version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    #restart: on-failure
    depends_on:
      - db
    environment:
      DB_PASSWORD: "qwerty"
      DB_HOST: db

  db:
    restart: always
    image: postgres:latest
    container_name: database
    volumes:
     - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5436:5432"