version: '3.8'

services:
  study-bot-tester:
    build:
      dockerfile: dockerfile-tester/Dockerfile
    container_name: study-bot-tester-app
    restart: on-failure
    depends_on:
      - study-bot-db
    environment:
      DB_PASSWORD: "qwerty"
      DB_HOST: study-bot-db

  study-bot-control:
    build:
      dockerfile: dockerfile-control/Dockerfile
    container_name: study-bot-control-app
   # restart: on-failure
    depends_on:
      - study-bot-db
    environment:
      DB_PASSWORD: "qwerty"
      DB_HOST: study-bot-db

  study-bot-db:
    restart: always
    image: postgres:latest
    container_name: study-bot-database
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5436:5432"